// src/app/privacy-policy/privacy-policy.component.ts
import { Component, inject } from '@angular/core';
import { AppComponent } from '../app.component';

@Component({
  selector: 'app-privacy-policy',
  standalone: true,
  imports: [],
  templateUrl: './privacy-policy.component.html',
  styleUrl: './privacy-policy.component.scss'
})
export class PrivacyPolicyComponent {
  appComponent: AppComponent = inject(AppComponent);
}

<section>
    @if (appComponent.chosenLanguege === 'EN') {
    <h1>Privacy policy</h1>
    <h3>General information</h3>
    <p>
        The following information provides a simple overview of what is done with your personal data.
        data
        when you visit this website. Personal data is all data with which you
        personally
        can be identified. Detailed information on the subject of data protection can be found in
        our
        data protection declaration listed below this text.
    </p>
    <h3>Data collection on this website</h3>
    <h4>Who is responsible for data collection on this website?</h4>
    <p>
        Data processing on this website is carried out by the website operator. The operator's contact details can be
        you
        the section &bdquo;Note on the responsible body&ldquo; in this privacy policy
        in this privacy policy.
    </p>
    <h4>How do we collect your data?</h4>
    <p>
        On the one hand, your data is collected when you provide it to us. This can be, for example
        to
        data that you enter in a contact form.
    </p>
    <p>
        Other data is collected automatically or with your consent by our IT systems when you visit the website.
        collected. This is primarily technical data (e.g. internet browser, operating system or time of the page view).
        This data is collected automatically as soon as you enter this website.
    </p>
    <h4>What do we use your data for?</h4>
    <p>
        Some of the data is collected in order to ensure error-free provision of the website. Other
        data can be used to analyse your user behaviour.
    </p>
    <h4>What rights do you have with regard to your data?</h4>
    <p>
        You have the right to receive information free of charge at any time about the origin, recipient and purpose of
        your
        stored personal data. You also have the right to request the correction or deletion of this data.
        erasure of this data. If you have given your consent to data processing,
        you can revoke this consent at any time for the future. Furthermore, you have the
        right, under certain circumstances, to request the restriction of the processing of your personal data.
        to
        request. You also have the right to lodge a complaint with the competent supervisory authority.
    </p>
    } @else {
    <h1>Datenschutz&shy;erkl&auml;rung</h1>
    <h3>Allgemeine Hinweise</h3>
    <p>
        Die folgenden Hinweise geben einen einfachen &Uuml;berblick dar&uuml;ber, was mit Ihren personenbezogenen
        Daten
        passiert, wenn Sie diese Website besuchen. Personenbezogene Daten sind alle Daten, mit denen Sie
        pers&ouml;nlich
        identifiziert werden k&ouml;nnen. Ausf&uuml;hrliche Informationen zum Thema Datenschutz entnehmen Sie
        unserer
        unter diesem Text aufgef&uuml;hrten Datenschutzerkl&auml;rung.
    </p>
    <h3>Datenerfassung auf dieser Website</h3>
    <h4>Wer ist verantwortlich f&uuml;r die Datenerfassung auf dieser Website?</h4>
    <p>
        Die Datenverarbeitung auf dieser Website erfolgt durch den Websitebetreiber. Dessen Kontaktdaten k&ouml;nnen
        Sie
        dem Abschnitt &bdquo;Hinweis zur Verantwortlichen Stelle&ldquo; in dieser Datenschutzerkl&auml;rung
        entnehmen.
    </p>
    <h4>Wie erfassen wir Ihre Daten?</h4>
    <p>
        Ihre Daten werden zum einen dadurch erhoben, dass Sie uns diese mitteilen. Hierbei kann es sich z.&nbsp;B.
        um
        Daten handeln, die Sie in ein Kontaktformular eingeben.
    </p>
    <p>
        Andere Daten werden automatisch oder nach Ihrer Einwilligung beim Besuch der Website durch unsere IT-Systeme
        erfasst. Das sind vor allem technische Daten (z.&nbsp;B. Internetbrowser, Betriebssystem oder Uhrzeit des
        Seitenaufrufs). Die Erfassung dieser Daten erfolgt automatisch, sobald Sie diese Website betreten.
    </p>
    <h4>Wof&uuml;r nutzen wir Ihre Daten?</h4>
    <p>Ein Teil der Daten wird erhoben, um eine fehlerfreie Bereitstellung der Website zu gew&auml;hrleisten. Andere
        Daten k&ouml;nnen zur Analyse Ihres Nutzerverhaltens verwendet werden.
    </p>
    <h4>Welche Rechte haben Sie bez&uuml;glich Ihrer Daten?</h4>
    <p>
        Sie haben jederzeit das Recht, unentgeltlich Auskunft &uuml;ber Herkunft, Empf&auml;nger und Zweck Ihrer
        gespeicherten personenbezogenen Daten zu erhalten. Sie haben au&szlig;erdem ein Recht, die Berichtigung oder
        L&ouml;schung dieser Daten zu verlangen. Wenn Sie eine Einwilligung zur Datenverarbeitung erteilt haben,
        k&ouml;nnen Sie diese Einwilligung jederzeit f&uuml;r die Zukunft widerrufen. Au&szlig;erdem haben Sie das
        Recht, unter bestimmten Umst&auml;nden die Einschr&auml;nkung der Verarbeitung Ihrer personenbezogenen Daten
        zu
        verlangen. Des Weiteren steht Ihnen ein Beschwerderecht bei der zust&auml;ndigen Aufsichtsbeh&ouml;rde zu.
    </p>
    }
</section>

// app/privacy-policy/page.tsx
import React from "react";

const PrivacyPolicy = () => {
    return (
        <section className="flex flex-col items-center justify-center gap-4 text-center px-4 lg:max-w-[50vw] h-screen mx-auto">
            <h1 className="font-bold text-3xl md:text-4xl lg:text-5xl">Privacy policy</h1>
            <h3 className="font-semibold text-2xl md:text-3xl lg:text-4xl">General information</h3>
            <p>
                The following information provides a simple overview of what is done with your personal data.
                data
                when you visit this website. Personal data is all data with which you
                personally
                can be identified. Detailed information on the subject of data protection can be found in
                our
                data protection declaration listed below this text.
            </p>
            <h3 className="font-semibold text-2xl md:text-3xl lg:text-4xl">Data collection on this website</h3>
            <h4 className="font-medium text-xl md:text-2xl lg:text-3xl">Who is responsible for data collection on this website?</h4>
            <p>
                Data processing on this website is carried out by the website operator. The operator's contact details can be
                you
                the section &bdquo;Note on the responsible body&ldquo; in this privacy policy
                in this privacy policy.
            </p>
            <h4 className="font-medium text-xl md:text-2xl lg:text-3xl">How do we collect your data?</h4>
            <p>
                On the one hand, your data is collected when you provide it to us. This can be, for example
                to
                data that you enter in a contact form.
            </p>
            <p>
                Other data is collected automatically or with your consent by our IT systems when you visit the website.
                collected. This is primarily technical data (e.g. internet browser, operating system or time of the page view).
                This data is collected automatically as soon as you enter this website.
            </p>
            <h4 className="font-medium text-xl md:text-2xl lg:text-3xl">What do we use your data for?</h4>
            <p>
                Some of the data is collected in order to ensure error-free provision of the website. Other
                data can be used to analyse your user behaviour.
            </p>
            <h4 className="font-medium text-xl md:text-2xl lg:text-3xl">What rights do you have with regard to your data?</h4>
            <p>
                You have the right to receive information free of charge at any time about the origin, recipient and purpose of
                your
                stored personal data. You also have the right to request the correction or deletion of this data.
                erasure of this data. If you have given your consent to data processing,
                you can revoke this consent at any time for the future. Furthermore, you have the
                right, under certain circumstances, to request the restriction of the processing of your personal data.
                to
                request. You also have the right to lodge a complaint with the competent supervisory authority.
            </p>
        </section>
    );
};

export default PrivacyPolicy;
